<h3> Basic Math and Statistics </h3>

In [1]:
import numpy as np
from numpy.random import randn

In [2]:
# setting the decimal precision 
np.set_printoptions(precision=2)

In [3]:
# creating array using list
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
# Creating matrix
b=np.array([[1,2,3,4,5],[1,2,3,4]])
b

array([[1, 2, 3, 4, 5], [1, 2, 3, 4]], dtype=object)

In [5]:
np.random.seed(60)
c=36*np.random.randn(6)
c

array([-33.18, -21.11,  41.9 , -44.7 , -71.47,  47.04])

In [6]:
# creating a series of values
d=np.arange(1,36)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35])

In [7]:
# Performing Mathematics on Array
a*10

array([10, 20, 30, 40, 50, 60])

In [8]:
c+a

array([-32.18, -19.11,  44.9 , -40.7 , -66.47,  53.04])

In [9]:
c-a

array([-34.18, -23.11,  38.9 , -48.7 , -76.47,  41.04])

In [10]:
c*a

array([ -33.18,  -42.21,  125.71, -178.81, -357.34,  282.25])

In [11]:
c/a

array([-33.18, -10.55,  13.97, -11.18, -14.29,   7.84])

In [12]:
# Matrix
aa=np.array([[2,4,6],[1,3,5],[10,20,30]])
aa

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [10, 20, 30]])

In [13]:
bb=np.array([[0,1,2],[3,4,5],[6,7,8]])
bb

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
aa*bb

array([[  0,   4,  12],
       [  3,  12,  25],
       [ 60, 140, 240]])

In [15]:
# Matrix Multiplication ( dot operation)
np.dot(aa,bb)

array([[ 48,  60,  72],
       [ 39,  48,  57],
       [240, 300, 360]])